### ISSUE TITLE
Doc to avoid forgetting stuff

### ISSUE THREAD

**Issue by LePhenix47** [LePhenix47/Dev-Portfolio-Back-End_Younes-Lahouiti#4]
# VPS Setup and Deployment Notes

## User Permissions

- **Root user**: Has full control, including ability to edit system files and configs.
- **Deployer user**: Limited user for running deployments.
  - Can run `docker-compose` to manage containers.
  - Can read (but **not** edit) certain config files owned by root, like `/etc/caddy/Caddyfile`.
  - Home directory: `/home/deployer`

**Note**: Root can change permissions or create symlinks for deployer to access configs safely.

---

## Caddy Configuration

- Caddy runs as a system service, config located at `/etc/caddy/Caddyfile`.
- Caddyfile uses `handle_path` to separate APIs by URL path.

Current Caddyfile example:

```Caddyfile
youneslahouiti.com {
    root * /usr/share/caddy
    file_server

    # Portfolio API reverse proxy
    handle_path /portfolio/api/* {
        rewrite * /api{path}
        reverse_proxy localhost:3000
    }

    # Chess API (planned)
    # handle_path /chess/api/* {
    #     reverse_proxy localhost:4000
    # }
}

import sites-enabled/*
```

- After changes, reload Caddy with:  
`sudo service caddy reload`

- Check status with:  
`sudo service caddy status`

---

## Docker Compose (Backend)

File location: `/home/deployer/docker-compose.yml`

```yaml
version: "3"

services:
backend:
  env_file:
    - .env # This should be in the same folder where you run docker-compose
  image: lephenix47/dev-portfolio-bun-hono-backend:latest # Use the pre-built image
  ports:
    - "3000:3000"
  restart: always # Ensures the container restarts if it crashes
```

- Run with:  
`docker compose up -d`

- Note: `version: "3"` is obsolete but harmless here.

---

## Testing API

- Direct container API calls work:  
`curl -i http://localhost:3000/api/doc`

 External via Caddy reverse proxy:  

---

This setup lets you securely run multiple APIs on the same VPS with clear user permission separation and easy reloads of the web server config.

---

If you want, I can help you prepare a ready-to-publish README or issue on GitHub with this content. Just say the word!
